/* © SRSoftware 2024 */
package de.srsoftware.oidc.api;


public class Constants {
	public static final String ACCESS_TOKEN	  = "access_token";
	public static final String APP_NAME	  = "LightOIDC";
	public static final String AT_HASH	  = "at_hash";
	public static final String AUTH_CODE	  = "authorization_code";
	public static final String AUTHORZED	  = "authorized";
	public static final String BEARER	  = "Bearer";
	public static final String CAUSE	  = "cause";
	public static final String CLIENT_ID	  = "client_id";
	public static final String CLIENT_SECRET	  = "client_secret";
	public static final String CODE		  = "code";
	public static final String EMAIL	  = "email";
	public static final String ERROR	  = "error";
	public static final String CONFIG_PATH	  = "LIGHTOIDC_CONFIG_PATH";
	public static final String CONFIRMED	  = "confirmed";
	public static final String DAYS		  = "days";
	public static final String ENCRYPTION_KEY	  = "encryption_key";
	public static final String ERROR_DESCRIPTION	  = "error_description";
	public static final String ERROR_LOCKED	  = "error_locked";
	public static final String ERROR_LOGIN_FAILED	  = "error_login_failed";
	public static final String ERROR_NO_USERNAME	  = "error_no_username";
	public static final String EXPIRATION	  = "expiration";
	public static final String EXPIRES_IN	  = "expires_in";
	public static final String GRANT_TYPE	  = "grant_type";
	public static final String ID_TOKEN	  = "id_token";
	public static final String INVALID_CLIENT	  = "invalid_client";
	public static final String INVALID_GRANT	  = "invalid_grant";
	public static final String INVALID_REDIRECT_URI	  = "invalid_request_uri";
	public static final String INVALID_REQUEST	  = "invalid_request";
	public static final String INVALID_REQUEST_OBJECT = "invalid_request_object";
	public static final String INVALID_SCOPE	  = "invalid_scope";
	public static final String LANDING_PAGE	  = "landing_page";
	public static final String MAILCONFIG	  = "mail_config";
	public static final String NAME		  = "name";
	public static final String NONCE	  = "nonce";
	public static final String PERMISSION	  = "permission";
	public static final String OPENID	  = "openid";
	public static final String REDIRECT_URI	  = "redirect_uri";
	public static final String REDIRECT_URIS	  = "redirect_uris";
	public static final String REQUEST_NOT_SUPPORTED  = "request_not_supported";
	public static final String RESPONSE_TYPE	  = "response_type";
	public static final String SALT		  = "salt";
	public static final String SCOPE	  = "scope";
	public static final String SECRET	  = "secret";
	public static final String SESSION_DURATION	  = "session_duration";
	public static final String SMTP_USER	  = "smtp_user";
	public static final String SMTP_PASSWORD	  = "smtp_pass";
	public static final String SMTP_AUTH	  = "smtp_auth";
	public static final String SMTP_HOST	  = "smtp_host";
	public static final String SMTP_PORT	  = "smtp_port";
	public static final String STATE	  = "state";
	public static final String START_TLS	  = "start_tls";
	public static final String TOKEN	  = "token";
	public static final String TOKEN_TYPE	  = "token_type";
	public static final String TRUST	  = "trust";
	public static final String UNAUTHORIZED_CLIENT	  = "unauthorized_client";
	public static final String USER		  = "user";
	public static final String USER_ID	  = "user_id";
}
